export const IAM_CONSTANTS_ENVS = {
  IAM_CORE_SLUG: "IAM_CORE_SLUG",
  IAM_CORE_CLIENT_ID: "IAM_CORE_CLIENT_ID",
  IAM_CORE_UI_CLIENT_ID: "IAM_CORE_UI_CLIENT_ID",

  IAM_CORE_SYSTEM_API_RESOURCE_SERVER_NAME:
    "IAM_CORE_SYSTEM_API_RESOURCE_SERVER_NAME",
  IAM_CORE_SYSTEM_API_RESOURCE_SERVER_NAME_SLUG:
    "IAM_CORE_SYSTEM_API_RESOURCE_SERVER_NAME_SLUG",
  IAM_CORE_SYSTEM_API_RESOURCE_SERVER_CLIENT_ID:
    "IAM_CORE_SYSTEM_API_RESOURCE_SERVER_CLIENT_ID",
  IAM_CORE_SYSTEM_API_RESOURCE_SERVER_CLIENT_SECRET:
    "IAM_CORE_SYSTEM_API_RESOURCE_SERVER_CLIENT_SECRET",
};
