export const JWT_CONSTANTS = {
  REFRESH_TOKEN_SECRET: "REFRESH_TOKEN_SECRET",
  RSA_PUBLIC_KEY_SECRET: "RSA_PUBLIC_KEY_SECRET",
  RSA_PRIVATE_KEY_SECRET: "RSA_PRIVATE_KEY_SECRET",
};

export const JWT_EXPIRATION_TIMES = {
  M2M_TOKEN_EXPIRATION_TIME: "M2M_TOKEN_EXPIRATION_TIME",
  ACCESS_TOKEN_EXPIRATION_TIME: "ACCESS_TOKEN_EXPIRATION_TIME",
  REFRESH_TOKEN_EXPIRATION_TIME: "REFRESH_TOKEN_EXPIRATION_TIME",
};

export const JWT_ALGORITHMS = {
  M2M_TOKEN: "RS256",
  ACCESS_TOKEN: "RS256",
  REFRESH_TOKEN: "HS256",
};

export const JWT_SIGN_OPTIONS = {
  ISSUER: "ISSUER",
  AUDIENCE: "AUDIENCE",
};

export const JWT_EXTRACT_FIELDS = {
  ACCESS_TOKEN: {
    HEADER: "x-user-token",
  },
  REFRESH_TOKEN: {
    BODY: "refresh_token",
  },
};

export const JWT_STRATEGIES = {
  M2M_TOKEN: "M2M_TOKEN",
  ACCESS_TOKEN: "ACCESS_TOKEN",
  REFRESH_TOKEN: "REFRESH_TOKEN",
} as const;
