export const JWT_CONSTANTS = {
  REFRESH_TOKEN_SECRET: "REFRESH_TOKEN_SECRET",
  RSA_PUBLIC_KEY_SECRET: "RSA_PUBLIC_KEY_SECRET",
  RSA_PRIVATE_KEY_SECRET: "RSA_PRIVATE_KEY_SECRET",
};

export const JWT_EXPIRATION_TIMES = {
  S2S_TOKEN_EXPIRATION_TIME: "S2S_TOKEN_EXPIRATION_TIME",
  ACCESS_TOKEN_EXPIRATION_TIME: "ACCESS_TOKEN_EXPIRATION_TIME",
  REFRESH_TOKEN_EXPIRATION_TIME: "REFRESH_TOKEN_EXPIRATION_TIME",
};
