export const RATE_LIMIT_CONSTANTS = {
  RATE_LIMIT_MAX_ATTEMPTS: "RATE_LIMIT_MAX_ATTEMPTS",
  RATE_LIMIT_BLOCK_TIME_SECONDS: "RATE_LIMIT_BLOCK_TIME_SECONDS",
  RATE_LIMIT_WINDOW_TIME_SECONDS: "RATE_LIMIT_WINDOW_TIME_SECONDS",
};
