export const CRYPTO_HASH_CONSTANTS = {
  USER_CRYPTO_TIME_COST: "USER_CRYPTO_TIME_COST",
  USER_CRYPTO_MEMORY_COST: "USER_CRYPTO_MEMORY_COST",

  MACHINE_CRYPTO_TIME_COST: "MACHINE_CRYPTO_TIME_COST",
  MACHINE_CRYPTO_MEMORY_COST: "MACHINE_CRYPTO_MEMORY_COST",
};
